- hosts: "*"
  become: yes
  gather_facts: yes
  vars:
    playbook_name: "apt.yml"
  tasks:
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: yes
        autoremove: yes
      register: upgrade_result

    - name: Call notification runbook if upgrade happened
      ansible.builtin.include_playbook: notify_pushover.yml
      vars:
        message: >-
          Playbook {{ playbook_name }} finished.
          {% if upgrade_result.changed %}
            Upgrade was performed on the system.
          {% else %}
            No packages needed upgrading.
          {% endif %}
      when: upgrade_result.changed
