- hosts: "*"
  become: yes
  gather_facts: no   # No Python required
  tasks:
    - name: Update apt cache
      raw: sudo apt update -y

    - name: Upgrade all packages
      raw: sudo DEBIAN_FRONTEND=noninteractive apt upgrade -y

    - name: Remove unnecessary packages
      raw: sudo apt autoremove -y
