- hosts: "*"
  become: yes
  gather_facts: yes  # Python is required for apt module
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # optional: skip if cache is recent
      tags: update

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
      tags: upgrade

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes
      tags: cleanup
