- hosts: "*"
  become: yes
  gather_facts: yes  # Required for apt module
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: update

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: yes
        autoremove: yes
      register: upgrade_result
      tags: upgrade

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes
      tags: cleanup

    - name: Call Pushover notification runbook
      ansible.builtin.include_playbook:
        file: ../notify_pushover.yml
      vars:
        changes_status: "{{ 'Yes' if upgrade_result.changed else 'No' }}"
        playbook_name: "APT Upgrade"
      delegate_to: localhost
