- hosts: "*"
  become: yes
  vars_files:
    ansible_ssh_pass: "{{ lookup('env', 'SEMAPHORE_SECRET_USER_PASS') }}"
    ansible_become_password: "{{ lookup('env', 'SEMAPHORE_SECRET_USER_PASS') }}"
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'
        autoremove: 'yes'
