- hosts: "*"
  become: yes
  gather_facts: yes  # Python required for apt module
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # optional: skip if cache is recent
      tags: update

    - name: Upgrade all packages (normal upgrade)
      ansible.builtin.apt:
        upgrade: yes
        autoremove: yes
      tags: upgrade

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes
      tags: cleanup

    - name: Send Pushover notification
      ansible.builtin.uri:
        url: https://api.pushover.net/1/messages.json
        method: POST
        body:
          token: var.pover_token # Directly use the variable from the Variable Group
          user: var.pover_id   # Directly use the variable from the Variable Group
          message: "Task finished {{ ansible_job_id | default('manual-run') }}"
        body_format: form-urlencoded
