- hosts: "*"
  become: yes
  tasks:
    - name: Ensure required Python libraries are installed
      apt:
        name:
          - python3-apt
          - python3-six
        state: present
        update_cache: yes

    - name: Upgrade packages
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
