- hosts: "*"
  become: yes
  vars:
    ansible_ssh_pass: "{{ key_store.user_pass }}"
    ansible_become_password: "{{ key_store.user_pass }}"
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'
        autoremove: 'yes'
