- hosts: "*"
  become: yes
  gather_facts: no
  tasks:
    - name: Update apt cache
      raw: sudo apt update -y

    - name: Full upgrade all packages
      raw: sudo DEBIAN_FRONTEND=noninteractive apt full-upgrade -y

    - name: Remove unnecessary packages
      raw: sudo apt autoremove -y
