- hosts: "*"
  become: yes
  gather_facts: no   # Disable automatic fact gathering
  tasks:
    - name: Ensure required Python libraries are installed
      apt:
        name:
          - python3-apt
          - python3-six
        state: present
        update_cache: yes

    - name: Gather facts now that Python modules exist
      ansible.builtin.setup:

    - name: Upgrade packages
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
