- hosts: "*"
  become: yes
  vars:
    ansible_ssh_pass: ${user_pass}
    ansible_become_password: ${user_pass}
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'
        autoremove: 'yes'
