---
- name: Delete vzdump-qemu-107* backups on host2 with progress
  hosts: host2
  gather_facts: false
  become: true

  vars:
    dump_dir: "/var/lib/vz/dump"
    pattern: "vzdump-qemu-107*"

  tasks:
    - name: Ensure pv is installed (Debian/Ubuntu/Proxmox)
      ansible.builtin.apt:
        name: pv
        state: present
        update_cache: true

    - name: List matching files (no recurse)
      ansible.builtin.shell: |
        shopt -s nullglob
        ls -1 {{ dump_dir }}/{{ pattern }} 2>/dev/null || true
      args:
        executable: /bin/bash
      register: matches
      changed_when: false

    - name: Fail if nothing matched
      ansible.builtin.fail:
        msg: "No files matched {{ dump_dir }}/{{ pattern }}"
      when: matches.stdout_lines | length == 0

    - name: Show files to delete
      ansible.builtin.debug:
        var: matches.stdout_lines

    - name: Delete each file with progress output
      ansible.builtin.shell: |
        set -euo pipefail
        f="{{ item }}"
        echo "=== Deleting: $f ==="
        echo "--- Size:"
        ls -lh "$f" || true
        echo "--- Progress (reading file, then removing):"
        pv -p -t -e -r -a "$f" > /dev/null
        rm -f -- "$f"
        echo "=== Done: $f ==="
      args:
        executable: /bin/bash
      loop: "{{ matches.stdout_lines }}"
