---
- name: Delete vzdump-qemu-107* backups on host2 with progress
  hosts: host2
  gather_facts: false
  become: true

  vars:
    dump_dir: "/var/lib/vz/dump"
    pattern: "vzdump-qemu-107*"

  tasks:
    - name: Confirm pv exists
      ansible.builtin.command: "pv --version"
      register: pv_ver
      changed_when: false

    - name: List matching files (no recursion)
      ansible.builtin.shell: |
        shopt -s nullglob
        ls -1 {{ dump_dir }}/{{ pattern }} 2>/dev/null || true
      args:
        executable: /bin/bash
      register: matches
      changed_when: false

    - name: Show what will be deleted
      ansible.builtin.debug:
        var: matches.stdout_lines

    - name: Delete with progress (pv)
      ansible.builtin.shell: |
        set -euo pipefail
        f="{{ item }}"
        echo "=== Deleting: $f ==="
        ls -lh "$f" || true
        pv -p -t -e -r -a "$f" > /dev/null
        rm -f -- "$f"
        echo "=== Done: $f ==="
        df -h {{ dump_dir }} | tail -n +1
      args:
        executable: /bin/bash
      loop: "{{ matches.stdout_lines }}"
      when: matches.stdout_lines | length > 0
