---
- name: Delete vzdump-qemu-107* backups on host2 with progress
  hosts: host2
  gather_facts: false
  become: true

  vars:
    dump_dir: "/var/lib/vz/dump"
    pattern: "vzdump-qemu-107*"

  tasks:
    - name: List matching files
      ansible.builtin.shell: |
        shopt -s nullglob
        ls -1 {{ dump_dir }}/{{ pattern }} 2>/dev/null || true
      args:
        executable: /bin/bash
      register: matches
      changed_when: false

    - name: Delete with progress
      ansible.builtin.shell: |
        set -euo pipefail
        f="{{ item }}"
        echo "=== Deleting: $f ==="
        ls -lh "$f" || true
        pv -p -t -e -r -a "$f" > /dev/null
        rm -f -- "$f"
        echo "=== Done: $f ==="
      args:
        executable: /bin/bash
      loop: "{{ matches.stdout_lines }}"
      when: matches.stdout_lines | length > 0
