---
- name: Delete vzdump-qemu-107 backups on host2 (fast delete + clean up)
  hosts: host2
  gather_facts: false

  vars:
    dump_dir: "{{ dump_dir }}"
    vmid: "107"
    df_interval_seconds: 30
    df_loops: 6   # 6 * 30s = 3 minutes of updates

  tasks:
    - name: Heartbeat (start)
      ansible.builtin.command: date -Is
      register: ts_start
      changed_when: false

    - name: Show start time
      ansible.builtin.debug:
        msg: "Start: {{ ts_start.stdout }}"

    - name: List matching files
      ansible.builtin.shell: |
        shopt -s nullglob
        ls -1 {{ dump_dir }}/vzdump-qemu-{{ vmid }}* 2>/dev/null || true
      args:
        executable: /bin/bash
      register: matches
      changed_when: false

    - name: Show matching files
      ansible.builtin.debug:
        var: matches.stdout_lines

    - name: Show free space before delete
      ansible.builtin.command: df -h "{{ dump_dir }}"
      register: df_before
      changed_when: false

    - name: Free space before
      ansible.builtin.debug:
        var: df_before.stdout_lines

    - name: Delete backup archive(s) NOW (vma.zst only) + show df updates
      ansible.builtin.shell: |
        set -euo pipefail
        f="{{ item }}"
        D="{{ dump_dir }}"

        echo "=== Removing archive NOW: $f ==="
        ls -lh "$f" || true

        rm -f -- "$f"

        echo "=== Removed. Tracking free space ({{ df_loops }}x every {{ df_interval_seconds }}s) ==="
        for i in $(seq 1 {{ df_loops }}); do
          echo "--- df update #$i ---"
          df -h "$D" | tail -n +1
          sleep {{ df_interval_seconds }}
        done
        echo "=== Done tracking free space ==="
      args:
        executable: /bin/bash
      loop: "{{ matches.stdout_lines | select('match', '.*\\.vma\\.zst$') | list }}"
      when: (matches.stdout_lines | select('match', '.*\\.vma\\.zst$') | list) | length > 0

    - name: Delete notes/log leftovers (fast)
      ansible.builtin.shell: |
        shopt -s nullglob
        rm -f -- {{ dump_dir }}/vzdump-qemu-{{ vmid }}*.vma.zst.notes {{ dump_dir }}/vzdump-qemu-{{ vmid }}*.log
      args:
        executable: /bin/bash
      register: cleanup
      changed_when: cleanup.rc == 0

    - name: Show free space after delete
      ansible.builtin.command: df -h "{{ dump_dir }}"
      register: df_out
      changed_when: false

    - name: Free space after
      ansible.builtin.debug:
        var: df_out.stdout_lines

    - name: Heartbeat (end)
      ansible.builtin.command: date -Is
      register: ts_end
      changed_when: false

    - name: Show end time
      ansible.builtin.debug:
        msg: "End: {{ ts_end.stdout }}"
