- hosts: "*"
  become: yes
  gather_facts: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present

    - name: Enable and start qemu-guest-agent
      service:
        name: qemu-guest-agent
        enabled: yes
        state: started
