- hosts: "*"
  gather_facts: no
  tasks:
    - name: Update apt cache
      raw: sudo DEBIAN_FRONTEND=noninteractive apt-get update -y

    - name: Install qemu-guest-agent
      raw: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
           -o Dpkg::Options::="--force-confdef" \
           -o Dpkg::Options::="--force-confold" \
           qemu-guest-agent

    - name: Enable and start qemu-guest-agent
      raw: sudo systemctl enable --now qemu-guest-agent
