- name: Install and start qemu-guest-agent (raw)
  hosts: "*"
  gather_facts: no
  tasks:
    - name: Update apt cache
      raw: sudo apt update -y

    - name: Install qemu-guest-agent
      raw: sudo DEBIAN_FRONTEND=noninteractive apt install -y qemu-guest-agent

    - name: Enable and start qemu-guest-agent service
      raw: sudo systemctl enable --now qemu-guest-agent
