- hosts: "*"
  gather_facts: no
  tasks:
    - name: Update apt cache
      raw: sudo DEBIAN_FRONTEND=noninteractive apt update -y

    - name: Install qemu-guest-agent
      raw: sudo DEBIAN_FRONTEND=noninteractive apt install -y \
           -o Dpkg::Options::="--force-confdef" \
           -o Dpkg::Options::="--force-confold" qemu-guest-agent

    - name: Enable qemu-guest-agent service
      raw: sudo systemctl enable qemu-guest-agent

    - name: Start qemu-guest-agent service
      raw: sudo systemctl start qemu-guest-agent
