---
- name: Reboot all machines
  hosts: "*"
  become: yes
  gather_facts: no

  tasks:
    - name: Reboot the machine
      ansible.builtin.reboot:
        reboot_timeout: 600      # time to wait for machine to come back (seconds)
        pre_reboot_delay: 0      # delay before rebooting
        post_reboot_delay: 10    # wait after the host comes back up
        test_command: whoami     # checks if machine is ready
      register: reboot_result

    - name: Confirm machine is up
      ansible.builtin.ping:

    - name: Set reboot summary fact
      set_fact:
        reboot_success: "{{ reboot_result.changed | default(false) }}"
      run_once: true

- hosts: localhost
  gather_facts: no
  vars:
    playbook_name: "reboot.yml"
  tasks:
    - name: Send Pushover notification
      ansible.builtin.uri:
        url: https://api.pushover.net/1/messages.json
        method: POST
        body:
          token: "{{ pover_token }}"  # from Variable Group secret
          user: "{{ pover_id }}"      # from Variable Group secret
          message: >-
            Playbook {{ playbook_name }} finished.
            {% if hostvars | dict2items | selectattr('value.reboot_success', 'defined') | selectattr('value.reboot_success') | list | length > 0 %}
              Machines rebooted successfully.
            {% else %}
              No reboots were performed or all machines were already up to date.
            {% endif %}
        body_format: form-urlencoded
      run_once: true
