- name: Reboot all machines
  hosts: "*"
  become: yes
  gather_facts: no

  tasks:
    - name: Schedule reboot in 1 minute (so playbook can finish)
      ansible.builtin.command: shutdown -r +1 "Reboot scheduled by Ansible/Semaphore"
      register: reboot_result
      changed_when: true

    - name: Set reboot summary fact
      set_fact:
        reboot_success: true

- hosts: localhost
  gather_facts: no
  vars:
    playbook_name: "reboot.yml"
  tasks:
    - name: Send Pushover notification
      ansible.builtin.uri:
        url: https://api.pushover.net/1/messages.json
        method: POST
        body:
          token: "{{ pover_token }}"  # from Variable Group secret
          user: "{{ pover_id }}"      # from Variable Group secret
          message: >-
            Playbook {{ playbook_name }} finished.
            {% if hostvars | dict2items | selectattr('value.reboot_success', 'defined') | selectattr('value.reboot_success') | list | length > 0 %}
              Machines rebooted successfully.
            {% else %}
              No reboots were performed or all machines were already up to date.
            {% endif %}
        body_format: form-urlencoded
      run_once: true
